/* Helper file with all the libraries */
#pragma once
#include "CameraLib.hpp"
#include "ColliderLib.hpp"
#include "LightLib.hpp"
#include "Physics.hpp"
#include "Debug.hpp"
#include "Model3D.hpp"
#include "Node.hpp"
#include "Node2D.hpp"
#include "Node3D.hpp"
#include "Sprite2D.hpp"
#include "Text2D.hpp"
#include "UpdateNode3D.hpp"
#include "Renderer.hpp"